"""Byte-for-byte parity tests for the SPD RNG/seed port against reference
values dumped from the original game's actual Java classes
(com.watabou.utils.Random, DungeonSeed, Dungeon.seedForDepth) for seed "MAB".

Reference values were generated by compiling and running those exact Java
sources (plus a stub for their one Game.reportException dependency) against
a small harness that pushes generator(seed) and dumps draw sequences. These
numbers are NOT guesses; they are ground truth produced by SPD's own code.
"""

from app.engine.dungeon.dungeon_seed import (
    convert_from_text,
    convert_to_code,
    seed_for_depth,
)
from app.engine.dungeon.spd_random import SPDRandom

MAB_SEED = 76078


def test_mab_seed_conversion():
    assert convert_from_text("MAB") == MAB_SEED
    assert convert_to_code(MAB_SEED) == "AAA-AAE-IOC"


def test_other_seed_conversions():
    assert convert_from_text("ZZZ") == 89370
    assert convert_from_text("AAA") == 64545
    assert convert_from_text("123") == 123
    assert convert_from_text("hello") == 99162322


def test_seed_for_depth_matches_reference():
    expected = {
        1: 3436070614799102493,
        2: -8669563277299376600,
        3: -621634685520687361,
        4: -4381107783969769866,
        5: -993338270243451159,
        6: 7963183712798540150,
        26: 288533933944718135,
    }
    for depth, expected_seed in expected.items():
        assert seed_for_depth(MAB_SEED, depth, 0) == expected_seed


def _rng():
    rng = SPDRandom()
    rng.push_generator(MAB_SEED)
    return rng


def test_long_sequence_matches_reference():
    rng = _rng()
    assert [rng.Long() for _ in range(5)] == [
        1056737000723184707,
        3436070614799102493,
        -8669563277299376600,
        -621634685520687361,
        -4381107783969769866,
    ]


def test_int_sequence_matches_reference():
    rng = _rng()
    assert [rng.Int() for _ in range(5)] == [
        246040756, 220068931, 800022533, -498978275, -2018539998,
    ]


def test_float_sequence_matches_reference():
    rng = _rng()
    expected = [0.057285786, 0.051238775, 0.18626976, 0.88382256, 0.530022]
    for got, want in zip([rng.Float() for _ in range(5)], expected):
        assert abs(got - want) < 1e-6


def test_int_max_and_int_range_match_reference():
    rng = _rng()
    assert [rng.IntMax(100) for _ in range(5)] == [78, 65, 66, 10, 49]

    rng = _rng()
    assert [rng.IntRange(2, 9) for _ in range(5)] == [2, 2, 3, 9, 6]


def test_long_max_matches_reference():
    rng = _rng()
    assert [rng.LongMax(1000) for _ in range(5)] == [707, 493, 207, 446, 941]


def test_chances_matches_reference():
    rng = _rng()
    weights = [1.0, 2.0, 0.0, 3.0]
    assert [rng.chances(weights) for _ in range(8)] == [0, 0, 1, 3, 3, 3, 3, 0]


def test_element_matches_reference():
    rng = _rng()
    names = ["a", "b", "c", "d", "e"]
    assert [rng.element(names) for _ in range(5)] == ["d", "a", "b", "a", "e"]


def test_float_range_matches_reference():
    rng = _rng()
    expected = [1.2291431, 1.2049551, 1.745079, 4.5352902, 3.120088]
    for got, want in zip([rng.FloatRange(1.0, 5.0) for _ in range(5)], expected):
        assert abs(got - want) < 1e-5


def test_normal_int_range_matches_reference():
    rng = _rng()
    assert [rng.NormalIntRange(1, 10) for _ in range(5)] == [1, 6, 8, 6, 8]


def test_shuffle_list_matches_reference():
    """Random.shuffle(List<T>) -- backed by Collections.shuffle (reverse Fisher-Yates)."""
    rng = _rng()
    items = list(range(10))
    rng.shuffle(items)
    assert items == [0, 4, 7, 3, 2, 5, 9, 1, 6, 8]


def test_shuffle_array_matches_reference():
    """Random.shuffle(T[]) -- a *different* (forward) shuffle than the List overload."""
    rng = _rng()
    items = list(range(10))
    rng.shuffle_array(items)
    assert items == [8, 7, 3, 9, 2, 1, 4, 0, 6, 5]


def test_generator_stack_push_pop():
    rng = SPDRandom()
    base_draw = rng.Int()
    rng.push_generator(MAB_SEED)
    seeded_draw = rng.Int()
    rng.pop_generator()
    assert rng.Int() != seeded_draw  # back on the base generator
    assert base_draw is not None  # sanity: base generator usable before/after


def test_pop_last_generator_raises():
    rng = SPDRandom()
    try:
        rng.pop_generator()
    except RuntimeError:
        pass
    else:
        raise AssertionError("expected RuntimeError when popping the last generator")
